#!/bin/sh
#
# @name ThunderFly balloon TF-B1
#
# @type Balloon
# @class Balloon
#
#
# @url https://github.com/ThunderFly-aerospace/TF-B1/
# @maintainer ThunderFly s.r.o.
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.sl_defaults


set MIXER IO_pass
set MIXER_AUX pass
set PWM_OUT 1234
